//{type:'ADD_TODO',text:'korte'}
export const SET_ARTIST = 'SET_ARTIST';
export const LOADING_ARTIST = 'LOADING_ARTIST';
export const LOADING_ARTIST_FINISHED = 'LOADING_ARTIST_FINISHED';
export const SET_ARTIST_DETAILS = 'SET_ARTIST_DETAILS';
export const SET_SPOTIFY_TRACK = 'SET_SPOTIFY_TRACK';
export const SET_SPOTIFY_ARTIST_DETAILS = 'SET_SPOTIFY_ARTIST_DETAILS';
export const SET_YOUTUBE_ARTIST = 'SET_YOUTUBE_ARTIST';
export const SET_YOUTUBE_VIDEO_DETAILS = 'SET_YOUTUBE_VIDEO_DETAILS';


export const SET_ALBUM = 'SET_ALBUM';
export const SET_ALBUM_DETAILS = 'SET_ALBUM_DETAILS';
export const SET_SPOTIFY_ALBUM = 'SET_ALBUM_ALBUM';
export const SET_SPOTIFY_ALBUM_DETAILS = 'SET_SPOTIFY_ALBUM_DETAILS';
